version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app/
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=yoko_tz_db
      - POSTGRES_USER=yoko_user
      - POSTGRES_PASSWORD=yoko_password
    depends_on:
      - db
    restart: always
    networks:
        - yoko_network

  db:
    image: "postgres"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=yoko_tz_db
      - POSTGRES_USER=yoko_user
      - POSTGRES_PASSWORD=yoko_password
    restart: always
    networks:
        - yoko_network

networks:
  yoko_network:
